"""
ValidationRule dataclass + DB persistence.
Rules are generated by the LLM from known-good sample data and stored per pipeline.
"""
from __future__ import annotations
import json
from dataclasses import dataclass, field
from typing import Optional
from backend.database import get_conn


@dataclass
class ValidationRule:
    pipeline_name: str
    column_name:   str
    rule_type:     str   # "range" | "enum" | "not_null"
    params:        dict  # rule-specific config
    fix_policy:    dict  # operation spec to auto-apply
    auto_fix:      bool  = True
    confidence:    str   = "high"  # "high" | "medium" | "low"
    source:        str   = "learned"
    id:            Optional[int] = field(default=None, repr=False)


def load_rules(pipeline_name: str, org_id: str = "default") -> list[ValidationRule]:
    with get_conn() as conn:
        rows = conn.execute(
            "SELECT * FROM rules WHERE pipeline_name = ? AND org_id = ?",
            (pipeline_name, org_id),
        ).fetchall()
    return [
        ValidationRule(
            id=r["id"],
            pipeline_name=r["pipeline_name"],
            column_name=r["column_name"],
            rule_type=r["rule_type"],
            params=json.loads(r["params"] or "{}"),
            fix_policy=json.loads(r["fix_policy"] or "{}"),
            auto_fix=bool(r["auto_fix"]),
            confidence=r["confidence"],
            source=r["source"],
        )
        for r in rows
    ]


def save_rule(rule: ValidationRule, org_id: str = "default") -> int:
    with get_conn() as conn:
        cur = conn.execute(
            """
            INSERT INTO rules
              (org_id, pipeline_name, column_name, rule_type, params,
               fix_policy, auto_fix, confidence, source, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
            """,
            (
                org_id, rule.pipeline_name, rule.column_name, rule.rule_type,
                json.dumps(rule.params), json.dumps(rule.fix_policy),
                1 if rule.auto_fix else 0,
                rule.confidence, rule.source,
            ),
        )
        return cur.lastrowid


def delete_rule(rule_id: int) -> None:
    with get_conn() as conn:
        conn.execute("DELETE FROM rules WHERE id = ?", (rule_id,))


def clear_rules(pipeline_name: str, org_id: str = "default") -> None:
    with get_conn() as conn:
        conn.execute(
            "DELETE FROM rules WHERE pipeline_name = ? AND org_id = ?",
            (pipeline_name, org_id),
        )
